name: "Build PDF"

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/moderncv/debian-texlive-docker:main
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build PDF
        run: latexmk ./resume.tex
      - name: Upload PDF
        uses: actions/upload-artifact@v3
        with:
          name: pooriaaskarim.resume.pdf
          path: ./pooriaaskarim.resume.pdf
