name: Render LaTeX Resume

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
    paths:
      - 'resume/**'  # Trigger only if files in the resume directory are changed
  workflow_dispatch:  # Allows manual triggering from the GitHub UI

permissions:
  contents: write  # Allow actions to push commits and create tags

jobs:
  versioning:
    runs-on: ubuntu-latest
    steps:
      # Call the reusable versioning workflow
      - name: Run versioning workflow
        id: versioning_step  # Give this step an ID to reference its outputs
        uses: ./.github/workflows/versioning.yml

  build:
    needs: versioning  # This job depends on the versioning job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Restore cache for LaTeX packages (TeX Live)
      - name: Cache LaTeX packages
        uses: actions/cache@v2
        with:
          path: /usr/local/texlive  # Path where TeX Live packages are installed
          key: ${{ runner.os }}-texlive-${{ hashFiles('resume/resume.tex') }}  # Cache based on OS and LaTeX file hash
          restore-keys: |
            ${{ runner.os }}-texlive-

      # Cache LaTeX build artifacts (auxiliary and output files)
      - name: Cache LaTeX build artifacts
        uses: actions/cache@v2
        with:
          path: ./resume  # Cache LaTeX intermediate files from the resume directory
          key: ${{ runner.os }}-latex-build-${{ hashFiles('resume/resume.tex') }}  # Cache key based on OS and file hash
          restore-keys: |
            ${{ runner.os }}-latex-build-

      # Set up LaTeX environment and compile
      - name: Set up LaTeX environment
        uses: dante-ev/latex-action@latest  # Use the latest LaTeX action
        with:
          root_file: 'resume/resume.tex'  # Specify the main LaTeX file in the resume directory

      # Rename the generated resume.pdf to PooriaAskariMoqaddam.resume.pdf
      - name: Rename PDF
        run: mv resume/resume.pdf resume/PooriaAskariMoqaddam.resume.pdf

      # Cleanup environment - remove unnecessary files
      - name: Cleanup LaTeX build artifacts
        run: |
          rm -f resume/*.aux resume/*.log resume/*.out resume/*.fls

      # Create a new tag for the release and push it
      - name: Create Git tag
        run: |
          git tag ${{ steps.versioning_step.outputs.new_tag }}  # Use the output from the reusable workflow
          git push origin ${{ steps.versioning_step.outputs.new_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload renamed resume to GitHub release
      - name: Upload renamed resume to GitHub release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.versioning_step.outputs.new_tag }}  # Use the output from the reusable workflow
          files: resume/PooriaAskariMoqaddam.resume.pdf  # Upload the renamed PDF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
