name: Versioning Workflow

on:
  workflow_call:  # This allows this workflow to be called by other workflows

jobs:
  versioning:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.version.outputs.new_tag }}  # Output the new tag
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get latest tag and increment version
        id: version
        run: |
          # Fetch the latest tags
          git fetch --tags
          
          # Get the latest tag, if available
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1` || echo "none")

          if [ "$LATEST_TAG" = "none" ]; then
            # If no tags exist, start from version 1
            VERSION=1
          else
            # Extract the version number from the latest tag (assuming format v<version_number>.<YYMONTHDD>)
            VERSION=$(echo $LATEST_TAG | sed 's/v\([0-9]*\)\..*/\1/')
            VERSION=$((VERSION + 1))  # Increment the version
          fi
          
          # Generate the new tag in v<version_number>.<YYMONTHDD> format
          NEW_TAG="v$VERSION.$(date +'%y')$(date +'%b' | tr '[:lower:]' '[:upper:]')$(date +'%d')"

          # Output the new tag to be used by the calling workflow
          echo "new_tag=$NEW_TAG" >> $GITHUB_OUTPUT
